
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://morfrqtrzsqoftyknwpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcmZycXRyenNxb2Z0eWtud3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDYxNDksImV4cCI6MjA1NzgyMjE0OX0.DOsD1unDQq1Peo695A8j6M5TCPWETiWLIooxjVXpSmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
